volumes:
  housemate-db:
services:
  db:
    restart: unless-stopped
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - housemate-db:/var/lib/db/data16
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 1s
      timeout: 5s
      retries: 25