source "https://rubygems.org"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem "faker", "~> 3.5"
end



gem "graphql", "~> 2.3"


gem "annotate", "~> 3.2"

gem "rack-cors", "~> 2.0"

gem "omniauth", "~> 2.1"

gem "bcrypt", "~> 3.1"

gem "jwt", "~> 2.9"

gem "dotenv-rails", "~> 3.1"
